<?php

// hook_webform_submission_render_alter
// https://drupal.org/node/1042330
function mywebform_webform_submission_render_alter(&$renderable) {

	if($renderable['#format'] == "html") {
		$breaker = "<br/>";
	}
	else {
		$breaker = "\n\n";
	}

	foreach (element_children($renderable) as $key) {
			// It depends on whether it is html or plain text email    
			$renderable[$key]['#title'] = $breaker. $renderable[$key]['#title'];
      if (isset($renderable[$key]['#component']['type']) && $renderable[$key]['#component']['type'] == 'fieldset') {
        $fieldset = &$renderable[$key];      
        foreach (element_children($fieldset) as $key2) {
          $fieldset[$key2]['#title'] = $breaker. $fieldset[$key2]['#title'];
      }
    }
  }
	

}
